In [15]:
# list comprehension
print([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
print([i for i in range(10)])

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [16]:
# functions

def square(x):
    return x**2

def sum(a, b):
    return a + b

In [17]:
b = [i**2 for i in range(10)] # list comprehension
print(b)

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]


In [18]:
print(list(map(square, a)))  # map

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]


In [19]:
squared = []                # for loop
for elem in a:
    squared.append(elem**2)
print(squared)
    

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]


In [2]:
import numpy as np
import pandas as pd

In [9]:
# Creating ndarrays
list1 = [[1, 2, 3, 4], [5, 6, 7, 8]]
print(list1.__class__)

# implicit data type
np1 = np.array(list1)
print(np1)

# explicitly specify the data type
np2 = np.array(list1, dtype="float64")
print(np2)

print(np1.__class__)
print("np1:", np1)
print(type(np1))
print(len(np1))
print(np1.shape)
print(np1.dtype)
print(len(np1[0]))

<type 'list'>
[[1 2 3 4]
 [5 6 7 8]]
[[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]]
<type 'numpy.ndarray'>
('np1:', array([[1, 2, 3, 4],
       [5, 6, 7, 8]]))
<type 'numpy.ndarray'>
2
(2, 4)
int64
4


In [43]:
# useful initialization functions
print(np.zeros(10))
print(np.zeros((3, 5)))
print(np.ones((2,4)))
print(np.arange(15).reshape(3,5))
print(np.identity(3))

[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
[[ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]]
[[ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


In [35]:
import random
dir(np.random)

['Lock',
 'RandomState',
 '__RandomState_ctor',
 '__all__',
 '__builtins__',
 '__doc__',
 '__file__',
 '__name__',
 '__package__',
 '__path__',
 '__warningregistry__',
 '_numpy_tester',
 'absolute_import',
 'bench',
 'beta',
 'binomial',
 'bytes',
 'chisquare',
 'choice',
 'dirichlet',
 'division',
 'exponential',
 'f',
 'gamma',
 'geometric',
 'get_state',
 'gumbel',
 'hypergeometric',
 'info',
 'laplace',
 'logistic',
 'lognormal',
 'logseries',
 'mtrand',
 'multinomial',
 'multivariate_normal',
 'negative_binomial',
 'noncentral_chisquare',
 'noncentral_f',
 'normal',
 'np',
 'operator',
 'pareto',
 'permutation',
 'poisson',
 'power',
 'print_function',
 'rand',
 'randint',
 'randn',
 'random',
 'random_integers',
 'random_sample',
 'ranf',
 'rayleigh',
 'sample',
 'seed',
 'set_state',
 'shuffle',
 'standard_cauchy',
 'standard_exponential',
 'standard_gamma',
 'standard_normal',
 'standard_t',
 'test',
 'triangular',
 'uniform',
 'vonmises',
 'wald',
 'warnings',
 'weibull',
 'zi

In [51]:
np.random.seed = 42
print(np.random.randn(15).reshape(3, 5))  # normal random numbers 0 mean 1 std dev.
print(np.random.random(15).reshape(3, 5)) # uniformly random numbers between 0 and 1

[[-0.71041716 -1.87447478  1.35595266  1.10088678  0.20716933]
 [ 1.01181281 -1.32603172  0.38821449  0.49799739 -0.13167796]
 [-0.9950178  -0.20152432  0.4833846  -0.59537684 -1.55537977]]
[[ 0.78236783  0.80077992  0.25186019  0.5392842   0.6188256 ]
 [ 0.33557804  0.17769449  0.79196865  0.94654557  0.06611434]
 [ 0.72625207  0.64899075  0.15511213  0.29458691  0.50823517]]


In [47]:
# create nd array with random numbers
import random
choices = [1, 3, 5, 7, 9]
print(np.array([random.choice(choices) for i in range(15)]).reshape(3, 5))
print(np.array([random.choice(range(15)) for i in range(15)]).reshape(3, 5))

[[1 7 7 5 7]
 [9 3 7 1 9]
 [1 3 1 5 7]]
[[ 4  4  3 13  2]
 [14 11 14  4  2]
 [ 7 11 12 13  3]]


### Selecting Columns and Rows

In [53]:
arr = np.arange(10)
arr[5]

5

In [54]:
print(arr[5:8]) 

[5 6 7]


In [17]:
arr[5:8] = 12
print(arr)

[ 0  1  2  3  4 12 12 12  8  9]


In [18]:
# Aliasing
a = [1, 2, 3, 4, 5]
b = a
print(b)
b = a[:]
b[1] = 42
print(a)
print(b)

[1, 2, 3, 4, 5]
[1, 2, 3, 4, 5]
[1, 42, 3, 4, 5]


In [55]:
arr = np.arange(15).reshape(3, 5)
print(arr[0])     # select 1st row (index 0)
print(arr[1, 2])  # select 2nd row (index 1), 3rd column (index 2)

[0 1 2 3 4]
7


In [85]:
print(arr)
print(arr[:2])  # till row 2
print(arr[1:])  # from row 1 onwards

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[0 1 2 3 4]
 [5 6 7 8 9]]
[[ 5  6  7  8  9]
 [10 11 12 13 14]]


In [89]:
print(arr[:, :2]) # all rows and first 2 columns
print(arr[:2,:2])

[[ 0  1]
 [ 5  6]
 [10 11]]
[[0 1]
 [5 6]]


In [94]:
# Transpose
t = np.arange(15).reshape(3, 5)
print(t)
print(t.shape)
tt = t.T
print(tt)
print(tt.shape)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
(3, 5)
[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]
(5, 3)


In [99]:
# dot product
a = [1, 2, 3]
b = [2, 3, 4]
print(np.dot(a, b))  # dot product of two vectors
print(np.dot(t, tt)) # matrix multiplication

20
[[ 30  80 130]
 [ 80 255 430]
 [130 430 730]]


In [108]:
# Universal functions (Unary)
arr = np.arange(1,10)
print("sqrt:",np.sqrt(arr))
print("exp:",np.exp(arr))
print("square:", np.square(arr))
print("log10:", np.log10(arr))  # log base 10
print("log:", np.log(arr))      # natural log (base e)

('sqrt:', array([ 1.        ,  1.41421356,  1.73205081,  2.        ,  2.23606798,
        2.44948974,  2.64575131,  2.82842712,  3.        ]))
('exp:', array([  2.71828183e+00,   7.38905610e+00,   2.00855369e+01,
         5.45981500e+01,   1.48413159e+02,   4.03428793e+02,
         1.09663316e+03,   2.98095799e+03,   8.10308393e+03]))
('square:', array([ 1,  4,  9, 16, 25, 36, 49, 64, 81]))
('log10:', array([ 0.        ,  0.30103   ,  0.47712125,  0.60205999,  0.69897   ,
        0.77815125,  0.84509804,  0.90308999,  0.95424251]))
('log:', array([ 0.        ,  0.69314718,  1.09861229,  1.38629436,  1.60943791,
        1.79175947,  1.94591015,  2.07944154,  2.19722458]))


In [116]:
# Universal function (Binary)
a = np.arange(1, 11)
b = np.arange(11, 21)
print(np.add(a, b))
print(np.subtract(b, a))
print(np.multiply(a, b))
print(np.divide(b, a))
print(np.greater_equal(b, a))

[12 14 16 18 20 22 24 26 28 30]
[10 10 10 10 10 10 10 10 10 10]
[ 11  24  39  56  75  96 119 144 171 200]
[11  6  4  3  3  2  2  2  2  2]
[ True  True  True  True  True  True  True  True  True  True]


In [117]:
x1 = [4, 2, 1]
x2 = [2, 2, 2]
print(np.greater_equal(x1, x2))
print(np.mod(x1, x2))

[ True  True False]
[0 0 1]


### Logical Operations

In [61]:
x1 = [True, False, True, False]
x2 = [True, True, False, False]
print(np.logical_and(x1, x2))
print(np.logical_or(x1, x2))
print(np.logical_xor(x1,x2))
print(np.logical_not(x1))

[ True False False False]
[ True  True  True False]
[False  True  True False]
[False  True False  True]


### Math and Stats built-in functions

In [63]:
# math and stat functions
arr = np.array([[0, 1, 2], [3, 2, 5], [6, 7, 2]])
print(arr.shape)
print(arr.mean())
print(arr.sum())
print(arr.std())
 


(3, 3)
3.11111111111
28
2.23330569358


In [68]:
# Combining Arrays
x = np.arange(10)
y = np.arange(10, 20)
z = np.arange(20, 30)
zp = np.array(list(zip(x, y, z))) # python 3 creates zip object
print(zp)
print(zp.shape)
print(zp.T)

[[ 0 10 20]
 [ 1 11 21]
 [ 2 12 22]
 [ 3 13 23]
 [ 4 14 24]
 [ 5 15 25]
 [ 6 16 26]
 [ 7 17 27]
 [ 8 18 28]
 [ 9 19 29]]
(10, 3)
[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]]


In [131]:
a = np.array([[1, 2, 3], [2, 3, 4]])
z = np.zeros((2, 1))
np.append(a, z, axis=1) # column bind

array([[ 1.,  2.,  3.,  0.],
       [ 2.,  3.,  4.,  0.]])

In [136]:
z2 = np.zeros((1, 3))
np.append(a, z2, axis=0) # row bind

array([[ 1.,  2.,  3.],
       [ 2.,  3.,  4.],
       [ 0.,  0.,  0.]])

In [73]:
# subsetting
d = np.array([
        [1, 2, 3],
        [1, 3, 4],
        [2, 2, 3],
        [2, 3, 4]
    ])
print(d[d[:, 1] == 3])

[[1 3 4]
 [2 3 4]]


In [77]:
x = np.arange(100)
print(np.mean(x))
print(np.median(x))
print(np.std(x))

49.5
49.5
28.8660700477


### Concatenating Numpy Arrays

In [78]:
arr = np.arange(12).reshape(3, 4)
cc = np.concatenate([arr, arr], axis=1) # along columns
cr = np.concatenate([arr, arr], axis=0) # along rows
print(cc)
print(cr)

[[ 0  1  2  3  0  1  2  3]
 [ 4  5  6  7  4  5  6  7]
 [ 8  9 10 11  8  9 10 11]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
